project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Get Learn Bioinformatics"
  image: "img/profile.png"
  favicon: "img/favicon.png"
  description: "Educational Website for Get Learn Bioinformatics"

  page-footer:
    left: "&copy; Copyright 2026, get-learn-bioinformatics"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

 # Top navigation bar
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Courses"
        href: Courses/index.qmd
      - text: "Projects"
        menu:
        - text: "Research Project"
          href: Projects_Publications/research_project.qmd
        - text: "Published Work"
          href: Projects_Publications/published_work.qmd
        - text: "Pipeline"
          href: Projects_Publications/pipeline.qmd          
      - text: "Sessions & Talks"
        href: Sessions_Talks/index.qmd
      - text: "Blog"
        href: blog/blog.qmd
      - text: "Team"
        menu:
        - text: "Founding Members"
          href: Founding_Member/index.qmd
        - text: "Research Assistant"
          href: Research_Assistant/index.qmd
        - text: "Campus Ambassador"
          href: Campus_Ambassador/index.qmd
      - text: "Contact"
        href: blog/blog.qmd
    right: []
    search: true
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true